//Home APIs
export const homeActions = {
  FETCH_FEATBLOGS: 'FETCH_FEATBLOGS',
  FETCH_FEATBLOGS_SUCCESS: 'FETCH_FEATBLOGS_SUCCESS',
  FETCH_FEATBLOGS_FAILED: 'FETCH_FEATBLOGS_FAILED',
  SUBSCRIBE_NEWSLETTER: 'SUBSCRIBE_NEWSLETTER',
  SUBSCRIBE_NEWSLETTER_FAILED: 'SUBSCRIBE_NEWSLETTER_FAILED',
  SUBSCRIBE_NEWSLETTER_SUCCESS: 'SUBSCRIBE_NEWSLETTER_SUCCESS',
  SUBSCRIBE_RESET_RESULT: 'SUBSCRIBE_RESET_RESULT',
};

export const userActTypes = {
  LOGIN: 'LOGIN',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  FETCH_PROFILE: 'FETCH_PROFILE',
  FETCH_PROFILE_SUCCESS: 'FETCH_PROFILE_SUCCESS',
  REGISTER_USER: 'REGISTER_USER',
  REGISTER_USER_SUCCESS: 'REGISTER_USER_SUCCESS',
  LOGOUT: 'LOGOUT',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
}

export const sellDomainTypes = {
  SELL_DOMAIN: 'SELL_DOMAIN',
  SELL_DOMAIN_SUCCESS: 'SELL_DOMAIN_SUCCESS',
  SALE: 'SALE',
  TRAFFIC: 'TRAFFIC',
}

export const buyDomainTypes = {
  GET_BUY_DOMAIN: 'GET_BUY_DOMAIN',
  GET_BUY_DOMAIN_SUCCESS: 'GET_BUY_DOMAIN_SUCCESS',
  GET_BUY_DOMAIN_FAILED: 'GET_BUY_DOMAIN_FAILED',
  GET_BUY_DOMAIN_BY_ID: 'GET_BUY_DOMAIN_BY_ID',
  GET_BUY_DOMAIN_BY_ID_SUCCESS: 'GET_BUY_DOMAIN_BY_ID_SUCCESS',
  GET_BUY_DOMAIN_BY_ID_FAILED: 'GET_BUY_DOMAIN_BY_ID_FAILED',
}