//Home APIs
export const homeActions = {
  FETCH_FEATBLOGS: 'FETCH_FEATBLOGS',
  FETCH_FEATBLOGS_SUCCESS: 'FETCH_FEATBLOGS_SUCCESS',
  FETCH_FEATBLOGS_FAILED: 'FETCH_FEATBLOGS_FAILED',
  SUBSCRIBE_NEWSLETTER: 'SUBSCRIBE_NEWSLETTER',
  SUBSCRIBE_NEWSLETTER_FAILED: 'SUBSCRIBE_NEWSLETTER_FAILED',
  SUBSCRIBE_NEWSLETTER_SUCCESS: 'SUBSCRIBE_NEWSLETTER_SUCCESS',
  SUBSCRIBE_RESET_RESULT: 'SUBSCRIBE_RESET_RESULT',
};

export const userActTypes = {
  LOGIN: 'LOGIN',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  FETCH_PROFILE: 'FETCH_PROFILE',
  FETCH_PROFILE_SUCCESS: 'FETCH_PROFILE_SUCCESS',
}

export const sellDomainTypes = {
  SELL_DOMAIN: 'SELL_DOMAIN',
  SELL_DOMAIN_SUCCESS: 'SELL_DOMAIN_SUCCESS',
  PITCH: 'PITCH',
  PITCH_SUCCESS: 'PITCH_SUCCESS',
  SALE: 'SALE',
  SALE_SUCCESS: 'SALE_SUCCESS',
  TRAFFIC: 'TRAFFIC',
  TRAFFIC_SUCCESS: 'TRAFFIC_SUCCESS',
  PROMOTE: 'PROMOTE',
  PROMOTE_SUCCESS: 'PROMOTE_SUCCESS',
  VERIFY_TEXTFILE: 'VERIFY_TEXTFILE',
  VERIFY_TEXTFILE_SUCCESS: 'VERIFY_TEXTFILE_SUCCESS',
  GET_TEXT: 'GET_TEXT',
  GET_TEXT_SUCCESS: 'GET_TEXT_SUCCESS',
  VERIFY_META: 'VERIFY_META',
  VERIFY_META_SUCCESS: 'VERIFY_META_SUCCESS',
  GET_META: 'GET_META',
  GET_META_SUCCESS: 'GET_META_SUCCESS',
}